# app/schemas/workout.py
from pydantic import BaseModel, EmailStr, Field, ConfigDict
from datetime import datetime
from uuid import UUID
from typing import Optional

# Base — shared fields used by other schemas
class WorkoutBase(BaseModel):
    muscle_group: str = Field(min_length=1, max_length=50)
    day_of_week: str = Field(min_length=1, max_length=9)

# Create — fields needed when creating a new workout
# (no id, no timestamps — database generates those)
class WorkoutCreate(WorkoutBase):
    pass  # inherits everything from WorkoutBase

# Update — all fields optional since user may update only one field
class WorkoutUpdate(BaseModel):
    muscle_group: Optional[str] = Field(min_length=1, max_length=50)
    day_of_week: Optional[str] = Field(min_length=1, max_length=9)

# Response — what the API returns to the client
# (includes id and timestamps generated by the database)
class WorkoutResponse(WorkoutBase):
     model_config = ConfigDict(from_attributes=True) # so pydantic can read from SQLAlchemy model
     id: UUID
     user_id: UUID
     created_at: datetime
     updated_at: datetime