"""Changed columns nullable status to true

Revision ID: 74418cd2516b
Revises: bf1c37e7f00c
Create Date: 2026-09-17 22:07:10.098132+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74418cd2516b'
down_revision: Union[str, Sequence[str], None] = 'bf1c37e7f00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_exercises', 'set_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_exercises', 'rep_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_exercises', 'equipment_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('workout_exercises', 'kg_weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_exercises', 'kg_weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_exercises', 'equipment_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('workout_exercises', 'rep_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_exercises', 'set_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
