"""add columns to users table

Revision ID: bf1c37e7f00c
Revises: 9edc655e7e7a
Create Date: 2026-09-01 11:17:25.083626+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1c37e7f00c'
down_revision: Union[str, Sequence[str], None] = '9edc655e7e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_onboarded', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'has_onboarded')
    # ### end Alembic commands ###
