"""add conversation_scheduling_states

Revision ID: 9f3af4ae4329
Revises: 74418cd2516b
Create Date: 2026-09-24 13:11:30.428093+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3af4ae4329'
down_revision: Union[str, Sequence[str], None] = '74418cd2516b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_scheduling_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('flow', sa.String(length=32), nullable=False),
    sa.Column('step', sa.String(length=32), nullable=False),
    sa.Column('draft_day', sa.String(length=50), nullable=True),
    sa.Column('draft_muscle_group', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_scheduling_states_conversation_id'), 'conversation_scheduling_states', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversation_scheduling_states_id'), 'conversation_scheduling_states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_scheduling_states_id'), table_name='conversation_scheduling_states')
    op.drop_index(op.f('ix_conversation_scheduling_states_conversation_id'), table_name='conversation_scheduling_states')
    op.drop_table('conversation_scheduling_states')
    # ### end Alembic commands ###
